global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Scrape de microservi√ßos gRPC
  - job_name: "grpc_services"
    static_configs:
      - targets:
          - "modulo-a:5001"
          - "modulo-b:5002"
          - "modulo-p:8000"
